services:
  - type: web
    name: flask-socketio-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python MakeAction.py
    envVars:
      - key: FLASK_ENV
        value: production
